--- #YAML:1.0
name:                Querylet
version:             0.323
abstract:            simplified queries for the non-programmer
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    DBI:                           1
    Filter::Simple:                0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Ricardo SIGNES <rjbs@cpan.org>
