--- #YAML:1.0
name:                Querylet
version:             0.324
abstract:            simplified queries for the non-programmer
license:             perl
author:              
    - Ricardo SIGNES <rjbs@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    DBI:                           1
    Filter::Simple:                0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
